apiVersion: batch/v1
kind: Job
metadata:
  generateName: heavy-load-
spec:
  template:
    spec:
      containers:
      - name: work
        image: busybox
        command: ["sleep",  "300"]
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
      restartPolicy: Never
  backoffLimit: 4
  completions: 500
  parallelism: 500
